apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-webapp
  template:
    metadata:
      labels:
        app: jenkins-webapp
    spec:
      containers:
        - name: jenkinswebapp
          image: yogita077/jenkinswebapp
          ports:
            - containerPort: 80